<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="romrobillos" failures="2" tests="26" name="testcase.CartTest" time="198.384" errors="0" timestamp="2025-01-09T02:27:13 GMT+08:00" skipped="6">
  <testcase classname="testcase.CartTest" name="isAddedtoCartDisplayed" time="10.796">
    <skipped/>
  </testcase> <!-- isAddedtoCartDisplayed -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="isAddedtoCartDisplayed" time="6.116"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="isAddedtoCartDisplayed" time="15.993">
    <skipped/>
  </testcase> <!-- isAddedtoCartDisplayed -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="isAddedtoCartDisplayed" time="10.620"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="isAddedtoCartDisplayed" time="5.913"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toRemoveAllAddedItemsFromCart" time="6.852"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toRemoveAllAddedItemsFromCart" time="7.827"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toRemoveAllAddedItemsFromCart" time="3.875">
    <skipped/>
  </testcase> <!-- toRemoveAllAddedItemsFromCart -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="toRemoveAllAddedItemsFromCart" time="18.404"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toRemoveAllAddedItemsFromCart" time="4.333">
    <skipped/>
  </testcase> <!-- toRemoveAllAddedItemsFromCart -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="toCheckoutAllItems" time="5.789"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toCheckoutAllItems" time="11.186">
    <skipped/>
  </testcase> <!-- toCheckoutAllItems -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="toCheckoutAllItems" time="10.730">
    <skipped/>
  </testcase> <!-- toCheckoutAllItems -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="toCheckoutAllItems" time="6.516"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toCheckoutAllItems" time="10.876"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="testCheckoutBtnCoordinates" time="2.984">
    <failure message="The following asserts failed:
	expected [1045] but found [1060],
	expected [217] but found [0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1045] but found [1060],
expected [217] but found [0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcase.CartTest.testCheckoutBtnCoordinates(CartTest.java:369)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCheckoutBtnCoordinates -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="toContinueShopping" time="4.247"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toContinueShopping" time="3.791"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toContinueShopping" time="13.829"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toContinueShopping" time="3.857"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="toContinueShopping" time="3.945"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="testGlitchContinueShopping" time="4.417"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="testGlitchContinueShopping" time="13.972">
    <failure message="
Continue Shopping took 5.2896846 seconds expecting &lt;=1.0 seconds expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
Continue Shopping took 5.2896846 seconds expecting <=1.0 seconds expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcase.CartTest.testGlitchContinueShopping(CartTest.java:410)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testGlitchContinueShopping -->
  <system-out/>
  <testcase classname="testcase.CartTest" name="testGlitchContinueShopping" time="3.839"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="testGlitchContinueShopping" time="4.043"/>
  <system-out/>
  <testcase classname="testcase.CartTest" name="testGlitchContinueShopping" time="3.634"/>
  <system-out/>
</testsuite> <!-- testcase.CartTest -->
